name: Publish

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/**'

jobs:
  UpdateVersion:
    name: "Update Version"
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip bump]') || contains(github.event.head_commit.message, '[skip publish]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git";
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com";
          git config --local user.name "${GITHUB_ACTOR}";
        env:
          GITHUB_TOKEN: ${{ secrets.GH_COMMIT_TOKEN }}
      - name: Bump Semver
        run: yarn sversion
      - name: Commit changelog
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            exit 0;
          else
            git checkout -b master;
            git commit -sam "automated changelog";
            git push --set-upstream origin $(git rev-parse --abbrev-ref HEAD)
          fi

  Publish-NPM:
    name: "Publish to NPM"
    needs: UpdateVersion
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip bump]') || contains(github.event.head_commit.message, '[skip publish]') || contains(github.event.head_commit.message, '[skip publish-npm]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://registry.npmjs.org'
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  Publish-Github:
    name: "Publish to Github"
    needs: UpdateVersion
    runs-on: ubuntu-latest
    if: "!(contains(github.event.head_commit.message, '[skip ci]') || contains(github.event.head_commit.message, '[skip bump]') || contains(github.event.head_commit.message, '[skip publish]') || contains(github.event.head_commit.message, '[skip publish-github]'))"
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: "@quantumlytangled"
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --ignore-scripts --frozen-lockfile
      - name: Configure Git
        run: |
          git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git";
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com";
          git config --local user.name "${GITHUB_ACTOR}";
        env:
          GITHUB_TOKEN: ${{ secrets.GH_COMMIT_TOKEN }}
      - name: Publish
        run: |
          yarn run workflow:publish:github:replacename:linux
          yarn run workflow:publish:github:pipenpmrc:linux
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PUBLISH_TOKEN }}
